// Generated by CoffeeScript 1.3.3
(function() {
  var Emitter;

  Emitter = require("emitter");

  module.exports = function(element) {
    var emitter, initEvent, originX, originY, startX, startY;
    emitter = new Emitter;
    startX = 0;
    startY = 0;
    originX = 0;
    originY = 0;
    element.addEventListener("mousedown", initEvent = function(e) {
      var moveEvent, stopEvent;
      originX = element.offsetLeft;
      originY = element.offsetTop;
      startX = event.pageX;
      startY = event.pageY;
      emitter.emit("dragstart", {
        element: element,
        originX: originX,
        originY: originY,
        startX: startX,
        startY: startY
      });
      document.addEventListener("mousemove", moveEvent = function(e) {
        element.style["left"] = (originX + (e.pageX - startX)) + "px";
        element.style["top"] = (originY + (e.pageY - startY)) + "px";
        return emitter.emit("drag");
      });
      return document.addEventListener("mouseup", stopEvent = function(e) {
        var stopX, stopY;
        stopX = e.pageX;
        stopY = e.pageY;
        emitter.emit("dragstop", {
          element: element,
          originX: originX,
          originY: originY,
          startX: startX,
          startY: startY,
          stopX: stopX,
          stopY: stopY
        });
        document.removeEventListener("mousemove", moveEvent);
        return document.removeEventListener("mouseup", stopEvent);
      });
    });
    emitter.on("remove", function() {
      return element.removeEventListener("mousedown", initEvent);
    });
    return emitter;
  };

}).call(this);
